export enum NakamuraActions {
  LOAD_NAKAMURA_LIST = 'LOAD_NAKAMURA_LIST',
  SELECT_NAKAMURA_ITEM = 'SELECT_NAKAMURA_ITEM',
  UNSELECT_NAKAMURA_ITEM = 'UNSELECT_NAKAMURA_ITEM',
  TOGGLE_NAKAMURA_ITEM = 'TOGGLE_NAKAMURA_ITEM',
}